const ActionType={
    All : 'ALL',
    All_RESPONSE : 'ALL_RESPONSE',
    //user
    

    //LAHAN SATU
    LAHAN_SATU_KALIUM : 'LAHAN_SATU_KALIUM',
    LAHAN_SATU_KALIUM_RESPONSE : 'LAHAN_SATU_KALIUM_RESPONSE',
    LAHAN_SATU_NITROGEN : 'LAHAN_SATU_NITROGEN',
    LAHAN_SATU_NITROGEN_RESPONSE : 'LAHAN_SATU_NITROGEN_RESPONSE ',
    LAHAN_SATU_PH : 'LAHAN_SATU_PH',
    LAHAN_SATU_PH_RESPONSE : 'LAHAN_SATU_PH_RESPONSE',
    LAHAN_SATU_POTASIUM :  'LAHAN_SATU_POTASIUM',
    LAHAN_SATU_POTASIUM_RESPONSE : 'LAHAN_SATU_POTASIUM_RESPONSE ',
    LAHAN_SATU_KELEMBAPAN : 'LAHAN_SATU_KELEMBAPAN ',
    LAHAN_SATU_KELEMBAPAN_RESPONSE : 'LAHAN_SATU_KELEMBAPAN_RESPONSE',

    //LAHAN DUA
    LAHAN_DUA_KALIUM : 'LAHAN_DUA_KALIUM',
    LAHAN_DUA_KALIUM_RESPONSE : 'LAHAN_DUA_KALIUM_RESPONSE',
    LAHAN_DUA_NITROGEN : 'LAHAN_DUA_NITROGEN',
    LAHAN_DUA_NITROGEN_RESPONSE : 'LAHAN_DUA_NITROGEN_RESPONSE ',
    LAHAN_DUA_PH : 'LAHAN_DUA_PH',
    LAHAN_DUA_PH_RESPONSE : 'LAHAN_DUA_PH_RESPONSE',
    LAHAN_DUA_POTASIUM :  'LAHAN_DUA_POTASIUM',
    LAHAN_DUA_POTASIUM_RESPONSE : 'LAHAN_DUA_POTASIUM_RESPONSE ',
    LAHAN_DUA_KELEMBAPAN : 'LAHAN_DUA_KELEMBAPAN ',
    LAHAN_DUA_KELEMBAPAN_RESPONSE : 'LAHAN_DUA_KELEMBAPAN_RESPONSE',

    //LAHAN TIGA
    LAHAN_TIGA_KALIUM : 'LAHAN_TIGA_KALIUM',
    LAHAN_TIGA_KALIUM_RESPONSE : 'LAHAN_TIGA_KALIUM_RESPONSE',
    LAHAN_TIGA_NITROGEN : 'LAHAN_TIGA_NITROGEN',
    LAHAN_TIGA_NITROGEN_RESPONSE : 'LAHAN_TIGA_NITROGEN_RESPONSE ',
    LAHAN_TIGA_PH : 'LAHAN_TIGA_PH',
    LAHAN_TIGA_PH_RESPONSE : 'LAHAN_TIGA_PH_RESPONSE',
    LAHAN_TIGA_POTASIUM :  'LAHAN_TIGA_POTASIUM',
    LAHAN_TIGA_POTASIUM_RESPONSE : 'LAHAN_TIGA_POTASIUM_RESPONSE ',
    LAHAN_TIGA_KELEMBAPAN : 'LAHAN_TIGA_KELEMBAPAN ',
    LAHAN_TIGA_KELEMBAPAN_RESPONSE : 'LAHAN_TIGA_KELEMBAPAN_RESPONSE',

    //LAHAN EMPAT
    LAHAN_EMPAT_KALIUM : 'LAHAN_EMPAT_KALIUM',
    LAHAN_EMPAT_KALIUM_RESPONSE : 'LAHAN_EMPAT_KALIUM_RESPONSE',
    LAHAN_EMPAT_NITROGEN : 'LAHAN_EMPAT_NITROGEN',
    LAHAN_EMPAT_NITROGEN_RESPONSE : 'LAHAN_EMPAT_NITROGEN_RESPONSE ',
    LAHAN_EMPAT_PH : 'LAHAN_EMPAT_PH',
    LAHAN_EMPAT_PH_RESPONSE : 'LAHAN_EMPAT_PH_RESPONSE',
    LAHAN_EMPAT_POTASIUM :  'LAHAN_EMPAT_POTASIUM',
    LAHAN_EMPAT_POTASIUM_RESPONSE : 'LAHAN_EMPAT_POTASIUM_RESPONSE ',
    LAHAN_EMPAT_KELEMBAPAN : 'LAHAN_EMPAT_KELEMBAPAN ',
    LAHAN_EMPAT_KELEMBAPAN_RESPONSE : 'LAHAN_EMPAT_KELEMBAPAN_RESPONSE',

    //LAHAN SATU DATA BARU
LAHAN_SATU_KALIUM_BARU : 'LAHAN_SATU_KALIUM_BARU',
LAHAN_SATU_KALIUM_BARU_RESPONSE : 'LAHAN_SATU_KALIUM_BARU_RESPONSE',
LAHAN_SATU_NITROGEN_BARU : 'LAHAN_SATU_NITROGEN_BARU',
LAHAN_SATU_NITROGEN_BARU_RESPONSE : 'LAHAN_SATU_NITROGEN_BARU_RESPONSE ',
LAHAN_SATU_PH_BARU : 'LAHAN_SATU_PH_BARU',
LAHAN_SATU_PH_BARU_RESPONSE : 'LAHAN_SATU_PH_BARU_RESPONSE',
LAHAN_SATU_POTASIUM_BARU :  'LAHAN_SATU_POTASIUM_BARU',
LAHAN_SATU_POTASIUM_BARU_RESPONSE : 'LAHAN_SATU_POTASIUM_BARU_RESPONSE ',
LAHAN_SATU_KELEMBAPAN_BARU: 'LAHAN_SATU_KELEMBAPAN_BARU',
LAHAN_SATU_KELEMBAPAN_BARU_RESPONSE : 'LAHAN_SATU_KELEMBAPAN_BARU_RESPONSE',

//LAHAN DUA DATA BARU
LAHAN_DUA_KALIUM_BARU : 'LAHAN_DUA_KALIUM_BARU',
LAHAN_DUA_KALIUM_BARU_RESPONSE : 'LAHAN_DUA_KALIUM_BARU_RESPONSE',
LAHAN_DUA_NITROGEN_BARU : 'LAHAN_DUA_NITROGEN_BARU',
LAHAN_DUA_NITROGEN_BARU_RESPONSE : 'LAHAN_DUA_NITROGEN_BARU_RESPONSE ',
LAHAN_DUA_PH_BARU : 'LAHAN_DUA_PH_BARU',
LAHAN_DUA_PH_BARU_RESPONSE : 'LAHAN_DUA_PH_BARU_RESPONSE',
LAHAN_DUA_POTASIUM_BARU :  'LAHAN_DUA_POTASIUM_BARU',
LAHAN_DUA_POTASIUM_BARU_RESPONSE : 'LAHAN_DUA_POTASIUM_BARU_RESPONSE ',
LAHAN_DUA_KELEMBAPAN_BARU: 'LAHAN_DUA_KELEMBAPAN_BARU',
LAHAN_DUA_KELEMBAPAN_BARU_RESPONSE : 'LAHAN_DUA_KELEMBAPAN_BARU_RESPONSE',

//LAHAN TIGA DATA BARU
LAHAN_TIGA_KALIUM_BARU : 'LAHAN_TIGA_KALIUM_BARU',
LAHAN_TIGA_KALIUM_BARU_RESPONSE : 'LAHAN_TIGA_KALIUM_BARU_RESPONSE',
LAHAN_TIGA_NITROGEN_BARU : 'LAHAN_TIGA_NITROGEN_BARU',
LAHAN_TIGA_NITROGEN_BARU_RESPONSE : 'LAHAN_TIGA_NITROGEN_BARU_RESPONSE ',
LAHAN_TIGA_PH_BARU : 'LAHAN_TIGA_PH_BARU',
LAHAN_TIGA_PH_BARU_RESPONSE : 'LAHAN_TIGA_PH_BARU_RESPONSE',
LAHAN_TIGA_POTASIUM_BARU :  'LAHAN_TIGA_POTASIUM_BARU',
LAHAN_TIGA_POTASIUM_BARU_RESPONSE : 'LAHAN_TIGA_POTASIUM_BARU_RESPONSE ',
LAHAN_TIGA_KELEMBAPAN_BARU: 'LAHAN_TIGA_KELEMBAPAN_BARU',
LAHAN_TIGA_KELEMBAPAN_BARU_RESPONSE : 'LAHAN_TIGA_KELEMBAPAN_BARU_RESPONSE',

//LAHAN EMPAT DATA BARU
LAHAN_EMPAT_KALIUM_BARU : 'LAHAN_EMPAT_KALIUM_BARU',
LAHAN_EMPAT_KALIUM_BARU_RESPONSE : 'LAHAN_EMPAT_KALIUM_BARU_RESPONSE',
LAHAN_EMPAT_NITROGEN_BARU : 'LAHAN_EMPAT_NITROGEN_BARU',
LAHAN_EMPAT_NITROGEN_BARU_RESPONSE : 'LAHAN_EMPAT_NITROGEN_BARU_RESPONSE ',
LAHAN_EMPAT_PH_BARU : 'LAHAN_EMPAT_PH_BARU',
LAHAN_EMPAT_PH_BARU_RESPONSE : 'LAHAN_EMPAT_PH_BARU_RESPONSE',
LAHAN_EMPAT_POTASIUM_BARU :  'LAHAN_EMPAT_POTASIUM_BARU',
LAHAN_EMPAT_POTASIUM_BARU_RESPONSE : 'LAHAN_EMPAT_POTASIUM_BARU_RESPONSE ',
LAHAN_EMPAT_KELEMBAPAN_BARU: 'LAHAN_EMPAT_KELEMBAPAN_BARU',
LAHAN_EMPAT_KELEMBAPAN_BARU_RESPONSE : 'LAHAN_EMPAT_KELEMBAPAN_BARU_RESPONSE',

//login
LOGIN : 'LOGIN',
LOGIN_RESPONSE : 'LOGIN_RESPONSE',

//baruu
DATA_BARU_LAHAN_SATU : 'DATA_BARU_LAHAN_SATU',
DATA_BARU_LAHAN_SATU_RESPONSE : 'DATA_BARU_LAHAN_SATU_RESPONSE',
DATA_BARU_LAHAN_DUA : 'DATA_BARU_LAHAN_DUA',
DATA_BARU_LAHAN_DUA_RESPONSE : 'DATA_BARU_LAHAN_DUA_RESPONSE',
DATA_BARU_LAHAN_TIGA : 'DATA_BARU_LAHAN_TIGA',
DATA_BARU_LAHAN_TIGA_RESPONSE : 'DATA_BARU_LAHAN_TIGA_RESPONSE',
DATA_BARU_LAHAN_EMPAT : 'DATA_BARU_LAHAN_EMPAT',
DATA_BARU_LAHAN_EMPAT_RESPONSE : 'DATA_BARU_LAHAN_EMPAT_RESPONSE',

}

export default ActionType